//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name s from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCustomerByName", ReplyAction="*")]
        WebApplication3.ServiceReference1.getCustomerByNameResponse getCustomerByName(WebApplication3.ServiceReference1.getCustomerByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getCustomerByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.getCustomerByNameResponse> getCustomerByNameAsync(WebApplication3.ServiceReference1.getCustomerByNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerByName", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.getCustomerByNameRequestBody Body;
        
        public getCustomerByNameRequest() {
        }
        
        public getCustomerByNameRequest(WebApplication3.ServiceReference1.getCustomerByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCustomerByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string s;
        
        public getCustomerByNameRequestBody() {
        }
        
        public getCustomerByNameRequestBody(string s) {
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCustomerByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCustomerByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication3.ServiceReference1.getCustomerByNameResponseBody Body;
        
        public getCustomerByNameResponse() {
        }
        
        public getCustomerByNameResponse(WebApplication3.ServiceReference1.getCustomerByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getCustomerByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCustomerByNameResult;
        
        public getCustomerByNameResponseBody() {
        }
        
        public getCustomerByNameResponseBody(string getCustomerByNameResult) {
            this.getCustomerByNameResult = getCustomerByNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication3.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication3.ServiceReference1.WebService1Soap>, WebApplication3.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication3.ServiceReference1.getCustomerByNameResponse WebApplication3.ServiceReference1.WebService1Soap.getCustomerByName(WebApplication3.ServiceReference1.getCustomerByNameRequest request) {
            return base.Channel.getCustomerByName(request);
        }
        
        public string getCustomerByName(string s) {
            WebApplication3.ServiceReference1.getCustomerByNameRequest inValue = new WebApplication3.ServiceReference1.getCustomerByNameRequest();
            inValue.Body = new WebApplication3.ServiceReference1.getCustomerByNameRequestBody();
            inValue.Body.s = s;
            WebApplication3.ServiceReference1.getCustomerByNameResponse retVal = ((WebApplication3.ServiceReference1.WebService1Soap)(this)).getCustomerByName(inValue);
            return retVal.Body.getCustomerByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication3.ServiceReference1.getCustomerByNameResponse> WebApplication3.ServiceReference1.WebService1Soap.getCustomerByNameAsync(WebApplication3.ServiceReference1.getCustomerByNameRequest request) {
            return base.Channel.getCustomerByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication3.ServiceReference1.getCustomerByNameResponse> getCustomerByNameAsync(string s) {
            WebApplication3.ServiceReference1.getCustomerByNameRequest inValue = new WebApplication3.ServiceReference1.getCustomerByNameRequest();
            inValue.Body = new WebApplication3.ServiceReference1.getCustomerByNameRequestBody();
            inValue.Body.s = s;
            return ((WebApplication3.ServiceReference1.WebService1Soap)(this)).getCustomerByNameAsync(inValue);
        }
    }
}
