//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.KlijentAplikacija {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KlijentAplikacija.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURtoBAM", ReplyAction="*")]
        float konverzijaEURtoBAM(float e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaEURtoBAM", ReplyAction="*")]
        System.Threading.Tasks.Task<float> konverzijaEURtoBAMAsync(float e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMtoEUR", ReplyAction="*")]
        float konverzijaBAMtoEUR(float b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/konverzijaBAMtoEUR", ReplyAction="*")]
        System.Threading.Tasks.Task<float> konverzijaBAMtoEURAsync(float b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : WebApplication2.KlijentAplikacija.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<WebApplication2.KlijentAplikacija.WebService1Soap>, WebApplication2.KlijentAplikacija.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float konverzijaEURtoBAM(float e) {
            return base.Channel.konverzijaEURtoBAM(e);
        }
        
        public System.Threading.Tasks.Task<float> konverzijaEURtoBAMAsync(float e) {
            return base.Channel.konverzijaEURtoBAMAsync(e);
        }
        
        public float konverzijaBAMtoEUR(float b) {
            return base.Channel.konverzijaBAMtoEUR(b);
        }
        
        public System.Threading.Tasks.Task<float> konverzijaBAMtoEURAsync(float b) {
            return base.Channel.konverzijaBAMtoEURAsync(b);
        }
    }
}
